# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#CUNDINAMARCA Y MAGDALENA NO TIENEN CODIGO?!?
Department.create(id: 1, name: 'AMAZONAS', code: 91)
Department.create(id: 2, name: 'ANTIOQUIA', code: 5)
Department.create(id: 3, name: 'ARAUCA', code: 81)
Department.create(id: 4, name: 'ATLANTICO', code: 8)
Department.create(id: 5, name: 'BOLIVAR', code: 13)
Department.create(id: 6, name: 'BOYACA', code: 15)
Department.create(id: 7, name: 'CALDAS', code: 17)
Department.create(id: 8, name: 'CAQUETA', code: 18)
Department.create(id: 9, name: 'CASANARE', code: 85)
Department.create(id: 10, name: 'CAUCA', code: 19)
Department.create(id: 11, name: 'CESAR', code: 20)
Department.create(id: 12, name: 'CHOCO', code: 27)
Department.create(id: 13, name: 'CORDOBA', code: 23)
Department.create(id: 14, name: 'CUNDINAMARCA', code: 0)
Department.create(id: 15, name: 'DISTRITO CAPITAL', code: 11)
Department.create(id: 16, name: 'GUAINIA', code: 94)
Department.create(id: 17, name: 'GUAVIARE', code: 95)
Department.create(id: 18, name: 'HUILA', code: 41)
Department.create(id: 19, name: 'LA GUAJIRA', code: 44)
Department.create(id: 20, name: 'MAGDALENA', code: 0)
Department.create(id: 21, name: 'META', code: 50)
Department.create(id: 22, name: 'NARIÑO', code: 52)
Department.create(id: 23, name: 'N. DE SANTANDER', code: 54)
Department.create(id: 24, name: 'PUTUMAYO', code: 86)
Department.create(id: 25, name: 'QUINDIO', code: 63)
Department.create(id: 26, name: 'RISARALDA', code: 66)
Department.create(id: 27, name: 'SAN ANDRES', code: 88)
Department.create(id: 28, name: 'SANTANDER', code: 68)
Department.create(id: 29, name: 'SUCRE', code: 70)
Department.create(id: 30, name: 'TOLIMA', code: 73)
Department.create(id: 31, name: 'VALLE DEL CAUCA', code: 76)
Department.create(id: 32, name: 'VAUPEZ', code: 97)
Department.create(id: 33, name: 'VICHADA', code: 99)

#amazonas
City.create(name: 'LETICIA', code: 1, department_id: 1)
City.create(name: 'EL ENCANTO', code: 263, department_id: 1)
City.create(name: 'LA CHORRERA', code: 405, department_id: 1)
City.create(name: 'LA PEDRERA', code: 407, department_id: 1)
City.create(name: 'LA VICTORIA', code: 430, department_id: 1)
City.create(name: 'MIRITI - PARANA', code: 460, department_id: 1)
City.create(name: 'PUERTO ALEGRIA', code: 530, department_id: 1)
City.create(name: 'PUERTO ARICA', code: 536, department_id: 1)
City.create(name: 'PUERTO NARI?O', code: 540, department_id: 1)
City.create(name: 'PUERTO SANTANDER', code: 669, department_id: 1)
City.create(name: 'TARAPACA', code: 798, department_id: 1)

#antioquia
City.create(name: 'MEDELLIN', code: 1, department_id: 2)
City.create(name: 'ABEJORRAL', code: 2, department_id: 2)
City.create(name: 'ABRIAQUI', code: 4, department_id: 2)
City.create(name: 'ALEJANDRIA', code: 21, department_id: 2)
City.create(name: 'AMAGA', code: 30, department_id: 2)
City.create(name: 'AMALFI', code: 31, department_id: 2)
City.create(name: 'ANDES', code: 34, department_id: 2)
City.create(name: 'ANGELOPOLIS', code: 36, department_id: 2)
City.create(name: 'ANGOSTURA', code: 38, department_id: 2)
City.create(name: 'ANORI', code: 40, department_id: 2)
City.create(name: 'SANTAFE DE ANTIOQUIA', code: 42, department_id: 2)
City.create(name: 'ANZA', code: 44, department_id: 2)
City.create(name: 'APARTADO', code: 45, department_id: 2)
City.create(name: 'ARBOLETES', code: 51, department_id: 2)
City.create(name: 'ARGELIA', code: 55, department_id: 2)
City.create(name: 'ARMENIA', code: 59, department_id: 2)
City.create(name: 'BARBOSA', code: 79, department_id: 2)
City.create(name: 'BELMIRA', code: 86, department_id: 2)
City.create(name: 'BELLO', code: 88, department_id: 2)
City.create(name: 'BETANIA', code: 91, department_id: 2)
City.create(name: 'BETULIA', code: 93, department_id: 2)
City.create(name: 'CIUDAD BOLIVAR', code: 101, department_id: 2)
City.create(name: 'BRICE?O', code: 107, department_id: 2)
City.create(name: 'BURITICA', code: 113, department_id: 2)
City.create(name: 'CACERES', code: 120, department_id: 2)
City.create(name: 'CAICEDO', code: 125, department_id: 2)
City.create(name: 'CALDAS', code: 129, department_id: 2)
City.create(name: 'CAMPAMENTO', code: 134, department_id: 2)
City.create(name: 'CA?ASGORDAS', code: 138, department_id: 2)
City.create(name: 'CARACOLI', code: 142, department_id: 2)
City.create(name: 'CARAMANTA', code: 145, department_id: 2)
City.create(name: 'CAREPA', code: 147, department_id: 2)
City.create(name: 'EL CARMEN DE VIBORAL', code: 148, department_id: 2)
City.create(name: 'CAROLINA', code: 150, department_id: 2)
City.create(name: 'CAUCASIA', code: 154, department_id: 2)
City.create(name: 'CHIGORODO', code: 172, department_id: 2)
City.create(name: 'CISNEROS', code: 190, department_id: 2)
City.create(name: 'COCORNA', code: 197, department_id: 2)
City.create(name: 'CONCEPCION', code: 206, department_id: 2)
City.create(name: 'CONCORDIA', code: 209, department_id: 2)
City.create(name: 'COPACABANA', code: 212, department_id: 2)
City.create(name: 'DABEIBA', code: 234, department_id: 2)
City.create(name: 'DON MATIAS', code: 237, department_id: 2)
City.create(name: 'EBEJICO', code: 240, department_id: 2)
City.create(name: 'EL BAGRE', code: 250, department_id: 2)
City.create(name: 'ENTRERRIOS', code: 264, department_id: 2)
City.create(name: 'ENVIGADO', code: 266, department_id: 2)
City.create(name: 'FREDONIA', code: 282, department_id: 2)
City.create(name: 'FRONTINO', code: 284, department_id: 2)
City.create(name: 'GIRALDO', code: 306, department_id: 2)
City.create(name: 'GIRARDOTA', code: 308, department_id: 2)
City.create(name: 'GOMEZ PLATA', code: 310, department_id: 2)
City.create(name: 'GRANADA', code: 313, department_id: 2)
City.create(name: 'GUADALUPE', code: 315, department_id: 2)
City.create(name: 'GUARNE', code: 318, department_id: 2)
City.create(name: 'GUATAPE', code: 321, department_id: 2)
City.create(name: 'HELICONIA', code: 347, department_id: 2)
City.create(name: 'HISPANIA', code: 353, department_id: 2)
City.create(name: 'ITAGUI', code: 360, department_id: 2)
City.create(name: 'ITUANGO', code: 361, department_id: 2)
City.create(name: 'JARDIN', code: 364, department_id: 2)
City.create(name: 'JERICO', code: 368, department_id: 2)
City.create(name: 'LA CEJA', code: 376, department_id: 2)
City.create(name: 'LA ESTRELLA', code: 380, department_id: 2)
City.create(name: 'LA PINTADA', code: 390, department_id: 2)
City.create(name: 'LA UNION', code: 400, department_id: 2)
City.create(name: 'LIBORINA', code: 411, department_id: 2)
City.create(name: 'MACEO', code: 425, department_id: 2)
City.create(name: 'MARINILLA', code: 440, department_id: 2)
City.create(name: 'MONTEBELLO', code: 467, department_id: 2)
City.create(name: 'MURINDO', code: 475, department_id: 2)
City.create(name: 'MUTATA', code: 480, department_id: 2)
City.create(name: 'NARI?O', code: 483, department_id: 2)
City.create(name: 'NECOCLI', code: 490, department_id: 2)
City.create(name: 'NECHI', code: 495, department_id: 2)
City.create(name: 'OLAYA', code: 501, department_id: 2)
City.create(name: 'PE?OL', code: 541, department_id: 2)
City.create(name: 'PEQUE', code: 543, department_id: 2)
City.create(name: 'PUEBLORRICO', code: 576, department_id: 2)
City.create(name: 'PUERTO BERRIO', code: 579, department_id: 2)
City.create(name: 'PUERTO NARE', code: 585, department_id: 2)
City.create(name: 'PUERTO TRIUNFO', code: 591, department_id: 2)
City.create(name: 'REMEDIOS', code: 604, department_id: 2)
City.create(name: 'RETIRO', code: 607, department_id: 2)
City.create(name: 'RIONEGRO', code: 615, department_id: 2)
City.create(name: 'SABANALARGA', code: 628, department_id: 2)
City.create(name: 'SABANETA', code: 631, department_id: 2)
City.create(name: 'SALGAR', code: 642, department_id: 2)
City.create(name: 'SAN ANDRES DE CUERQUIA', code: 647, department_id: 2)
City.create(name: 'SAN CARLOS', code: 649, department_id: 2)
City.create(name: 'SAN FRANCISCO', code: 652, department_id: 2)
City.create(name: 'SAN JERONIMO', code: 656, department_id: 2)
City.create(name: 'SAN JOSE DE LA MONTA?A', code: 658, department_id: 2)
City.create(name: 'SAN JUAN DE URABA', code: 659, department_id: 2)
City.create(name: 'SAN LUIS', code: 660, department_id: 2)
City.create(name: 'SAN PEDRO', code: 664, department_id: 2)
City.create(name: 'SAN PEDRO DE URABA', code: 665, department_id: 2)
City.create(name: 'SAN RAFAEL', code: 667, department_id: 2)
City.create(name: 'SAN ROQUE', code: 670, department_id: 2)
City.create(name: 'SAN VICENTE', code: 674, department_id: 2)
City.create(name: 'SANTA BARBARA', code: 679, department_id: 2)
City.create(name: 'SANTA ROSA DE OSOS', code: 686, department_id: 2)
City.create(name: 'SANTO DOMINGO', code: 690, department_id: 2)
City.create(name: 'EL SANTUARIO', code: 697, department_id: 2)
City.create(name: 'SEGOVIA', code: 736, department_id: 2)
City.create(name: 'SONSON', code: 756, department_id: 2)
City.create(name: 'SOPETRAN', code: 761, department_id: 2)
City.create(name: 'TAMESIS', code: 789, department_id: 2)
City.create(name: 'TARAZA', code: 790, department_id: 2)
City.create(name: 'TARSO', code: 792, department_id: 2)
City.create(name: 'TITIRIBI', code: 809, department_id: 2)
City.create(name: 'TOLEDO', code: 819, department_id: 2)
City.create(name: 'TURBO', code: 837, department_id: 2)
City.create(name: 'URAMITA', code: 842, department_id: 2)
City.create(name: 'URRAO', code: 847, department_id: 2)
City.create(name: 'VALDIVIA', code: 854, department_id: 2)
City.create(name: 'VALPARAISO', code: 856, department_id: 2)
City.create(name: 'VEGACHI', code: 858, department_id: 2)
City.create(name: 'VENECIA', code: 861, department_id: 2)
City.create(name: 'VIGIA DEL FUERTE', code: 873, department_id: 2)
City.create(name: 'YALI', code: 885, department_id: 2)
City.create(name: 'YARUMAL', code: 887, department_id: 2)
City.create(name: 'YOLOMBO', code: 890, department_id: 2)
City.create(name: 'YONDO', code: 893, department_id: 2)
City.create(name: 'ZARAGOZA', code: 895, department_id: 2)

#arauca
City.create(name: 'ARAUCA', code: 1, department_id: 3)
City.create(name: 'ARAUQUITA', code: 65, department_id: 3)
City.create(name: 'CRAVO NORTE', code: 220, department_id: 3)
City.create(name: 'FORTUL', code: 300, department_id: 3)
City.create(name: 'PUERTO RONDON', code: 591, department_id: 3)
City.create(name: 'SARAVENA', code: 736, department_id: 3)
City.create(name: 'TAME', code: 794, department_id: 3)

#atlantico
City.create(name: 'BARRANQUILLA', code: 1, department_id: 4)
City.create(name: 'BARANOA', code: 78, department_id: 4)
City.create(name: 'CAMPO DE LA CRUZ', code: 137, department_id: 4)
City.create(name: 'CANDELARIA', code: 141, department_id: 4)
City.create(name: 'GALAPA', code: 296, department_id: 4)
City.create(name: 'JUAN DE ACOSTA', code: 372, department_id: 4)
City.create(name: 'LURUACO', code: 421, department_id: 4)
City.create(name: 'MALAMBO', code: 433, department_id: 4)
City.create(name: 'MANATI', code: 436, department_id: 4)
City.create(name: 'PALMAR DE VARELA', code: 520, department_id: 4)
City.create(name: 'PIOJO', code: 549, department_id: 4)
City.create(name: 'POLONUEVO', code: 558, department_id: 4)
City.create(name: 'PONEDERA', code: 560, department_id: 4)
City.create(name: 'PUERTO COLOMBIA', code: 573, department_id: 4)
City.create(name: 'REPELON', code: 606, department_id: 4)
City.create(name: 'SABANAGRANDE', code: 634, department_id: 4)
City.create(name: 'SABANALARGA', code: 638, department_id: 4)
City.create(name: 'SANTA LUCIA', code: 675, department_id: 4)
City.create(name: 'SANTO TOMAS', code: 685, department_id: 4)
City.create(name: 'SOLEDAD', code: 758, department_id: 4)
City.create(name: 'SUAN', code: 770, department_id: 4)
City.create(name: 'TUBARA', code: 832, department_id: 4)
City.create(name: 'USIACURI', code: 849, department_id: 4)

#bolivar
City.create(name: 'CARTAGENA', code: 1, department_id: 5)
City.create(name: 'ACHI', code: 6, department_id: 5)
City.create(name: 'ALTOS DEL ROSARIO', code: 30, department_id: 5)
City.create(name: 'ARENAL', code: 42, department_id: 5)
City.create(name: 'ARJONA', code: 52, department_id: 5)
City.create(name: 'ARROYOHONDO', code: 62, department_id: 5)
City.create(name: 'BARRANCO DE LOBA', code: 74, department_id: 5)
City.create(name: 'CALAMAR', code: 140, department_id: 5)
City.create(name: 'CANTAGALLO', code: 160, department_id: 5)
City.create(name: 'CICUCO', code: 188, department_id: 5)
City.create(name: 'CORDOBA', code: 212, department_id: 5)
City.create(name: 'CLEMENCIA', code: 222, department_id: 5)
City.create(name: 'EL CARMEN DE BOLIVAR', code: 244, department_id: 5)
City.create(name: 'EL GUAMO', code: 248, department_id: 5)
City.create(name: 'EL PE?ON', code: 268, department_id: 5)
City.create(name: 'HATILLO DE LOBA', code: 300, department_id: 5)
City.create(name: 'MAGANGUE', code: 430, department_id: 5)
City.create(name: 'MAHATES', code: 433, department_id: 5)
City.create(name: 'MARGARITA', code: 440, department_id: 5)
City.create(name: 'MARIA LA BAJA', code: 442, department_id: 5)
City.create(name: 'MONTECRISTO', code: 458, department_id: 5)
City.create(name: 'MOMPOS', code: 468, department_id: 5)
City.create(name: 'NOROSI', code: 490, department_id: 5)
City.create(name: 'MORALES', code: 473, department_id: 5)
City.create(name: 'PINILLOS', code: 549, department_id: 5)
City.create(name: 'REGIDOR', code: 580, department_id: 5)
City.create(name: 'RIO VIEJO', code: 600, department_id: 5)
City.create(name: 'SAN CRISTOBAL', code: 620, department_id: 5)
City.create(name: 'SAN ESTANISLAO', code: 647, department_id: 5)
City.create(name: 'SAN FERNANDO', code: 650, department_id: 5)
City.create(name: 'SAN JACINTO', code: 654, department_id: 5)
City.create(name: 'SAN JACINTO DEL CAUCA', code: 655, department_id: 5)
City.create(name: 'SAN JUAN NEPOMUCENO', code: 657, department_id: 5)
City.create(name: 'SAN MARTIN DE LOBA', code: 667, department_id: 5)
City.create(name: 'SAN PABLO', code: 670, department_id: 5)
City.create(name: 'SANTA CATALINA', code: 673, department_id: 5)
City.create(name: 'SANTA ROSA', code: 683, department_id: 5)
City.create(name: 'SANTA ROSA DEL SUR', code: 688, department_id: 5)
City.create(name: 'SIMITI', code: 744, department_id: 5)
City.create(name: 'SOPLAVIENTO', code: 760, department_id: 5)
City.create(name: 'TALAIGUA NUEVO', code: 780, department_id: 5)
City.create(name: 'TIQUISIO', code: 810, department_id: 5)
City.create(name: 'TURBACO', code: 836, department_id: 5)
City.create(name: 'TURBANA', code: 838, department_id: 5)
City.create(name: 'VILLANUEVA', code: 873, department_id: 5)
City.create(name: 'ZAMBRANO', code: 894, department_id: 5)

#boyaca
City.create(name: 'TUNJA', code: 1, department_id: 6)
City.create(name: 'ALMEIDA', code: 22, department_id: 6)
City.create(name: 'AQUITANIA', code: 47, department_id: 6)
City.create(name: 'ARCABUCO', code: 51, department_id: 6)
City.create(name: 'BELEN', code: 87, department_id: 6)
City.create(name: 'BERBEO', code: 90, department_id: 6)
City.create(name: 'BETEITIVA', code: 92, department_id: 6)
City.create(name: 'BOAVITA', code: 97, department_id: 6)
City.create(name: 'BOYACA', code: 104, department_id: 6)
City.create(name: 'BRICE?O', code: 106, department_id: 6)
City.create(name: 'BUENAVISTA', code: 109, department_id: 6)
City.create(name: 'BUSBANZA', code: 114, department_id: 6)
City.create(name: 'CALDAS', code: 131, department_id: 6)
City.create(name: 'CAMPOHERMOSO', code: 135, department_id: 6)
City.create(name: 'CERINZA', code: 162, department_id: 6)
City.create(name: 'CHINAVITA', code: 172, department_id: 6)
City.create(name: 'CHIQUINQUIRA', code: 176, department_id: 6)
City.create(name: 'CHISCAS', code: 180, department_id: 6)
City.create(name: 'CHITA', code: 183, department_id: 6)
City.create(name: 'CHITARAQUE', code: 185, department_id: 6)
City.create(name: 'CHIVATA', code: 187, department_id: 6)
City.create(name: 'CIENEGA', code: 189, department_id: 6)
City.create(name: 'COMBITA', code: 204, department_id: 6)
City.create(name: 'COPER', code: 212, department_id: 6)
City.create(name: 'CORRALES', code: 215, department_id: 6)
City.create(name: 'COVARACHIA', code: 218, department_id: 6)
City.create(name: 'CUBARA', code: 223, department_id: 6)
City.create(name: 'CUCAITA', code: 224, department_id: 6)
City.create(name: 'CUITIVA', code: 226, department_id: 6)
City.create(name: 'CHIQUIZA', code: 232, department_id: 6)
City.create(name: 'CHIVOR', code: 236, department_id: 6)
City.create(name: 'DUITAMA', code: 238, department_id: 6)
City.create(name: 'EL COCUY', code: 244, department_id: 6)
City.create(name: 'EL ESPINO', code: 248, department_id: 6)
City.create(name: 'FIRAVITOBA', code: 272, department_id: 6)
City.create(name: 'FLORESTA', code: 276, department_id: 6)
City.create(name: 'GACHANTIVA', code: 293, department_id: 6)
City.create(name: 'GAMEZA', code: 296, department_id: 6)
City.create(name: 'GARAGOA', code: 299, department_id: 6)
City.create(name: 'GUACAMAYAS', code: 317, department_id: 6)
City.create(name: 'GUATEQUE', code: 322, department_id: 6)
City.create(name: 'GUAYATA', code: 325, department_id: 6)
City.create(name: 'GsICAN', code: 332, department_id: 6)
City.create(name: 'IZA', code: 362, department_id: 6)
City.create(name: 'JENESANO', code: 367, department_id: 6)
City.create(name: 'JERICO', code: 368, department_id: 6)
City.create(name: 'LABRANZAGRANDE', code: 377, department_id: 6)
City.create(name: 'LA CAPILLA', code: 380, department_id: 6)
City.create(name: 'LA VICTORIA', code: 401, department_id: 6)
City.create(name: 'LA UVITA', code: 403, department_id: 6)
City.create(name: 'VILLA DE LEYVA', code: 407, department_id: 6)
City.create(name: 'MACANAL', code: 425, department_id: 6)
City.create(name: 'MARIPI', code: 442, department_id: 6)
City.create(name: 'MIRAFLORES', code: 455, department_id: 6)
City.create(name: 'MONGUA', code: 464, department_id: 6)
City.create(name: 'MONGUI', code: 466, department_id: 6)
City.create(name: 'MONIQUIRA', code: 469, department_id: 6)
City.create(name: 'MOTAVITA', code: 476, department_id: 6)
City.create(name: 'MUZO', code: 480, department_id: 6)
City.create(name: 'NOBSA', code: 491, department_id: 6)
City.create(name: 'NUEVO COLON', code: 494, department_id: 6)
City.create(name: 'OICATA', code: 500, department_id: 6)
City.create(name: 'OTANCHE', code: 507, department_id: 6)
City.create(name: 'PACHAVITA', code: 511, department_id: 6)
City.create(name: 'PAEZ', code: 514, department_id: 6)
City.create(name: 'PAIPA', code: 516, department_id: 6)
City.create(name: 'PAJARITO', code: 518, department_id: 6)
City.create(name: 'PANQUEBA', code: 522, department_id: 6)
City.create(name: 'PAUNA', code: 531, department_id: 6)
City.create(name: 'PAYA', code: 533, department_id: 6)
City.create(name: 'PAZ DE RIO', code: 537, department_id: 6)
City.create(name: 'PESCA', code: 542, department_id: 6)
City.create(name: 'PISBA', code: 550, department_id: 6)
City.create(name: 'PUERTO BOYACA', code: 572, department_id: 6)
City.create(name: 'QUIPAMA', code: 580, department_id: 6)
City.create(name: 'RAMIRIQUI', code: 599, department_id: 6)
City.create(name: 'RAQUIRA', code: 600, department_id: 6)
City.create(name: 'RONDON', code: 621, department_id: 6)
City.create(name: 'SABOYA', code: 632, department_id: 6)
City.create(name: 'SACHICA', code: 638, department_id: 6)
City.create(name: 'SAMACA', code: 646, department_id: 6)
City.create(name: 'SAN EDUARDO', code: 660, department_id: 6)
City.create(name: 'SAN JOSE DE PARE', code: 664, department_id: 6)
City.create(name: 'SAN LUIS DE GACENO', code: 667, department_id: 6)
City.create(name: 'SAN MATEO', code: 673, department_id: 6)
City.create(name: 'SAN MIGUEL DE SEMA', code: 676, department_id: 6)
City.create(name: 'SAN PABLO DE BORBUR', code: 681, department_id: 6)
City.create(name: 'SANTANA', code: 686, department_id: 6)
City.create(name: 'SANTA MARIA', code: 690, department_id: 6)
City.create(name: 'SANTA ROSA DE VITERBO', code: 693, department_id: 6)
City.create(name: 'SANTA SOFIA', code: 696, department_id: 6)
City.create(name: 'SATIVANORTE', code: 720, department_id: 6)
City.create(name: 'SATIVASUR', code: 723, department_id: 6)
City.create(name: 'SIACHOQUE', code: 740, department_id: 6)
City.create(name: 'SOATA', code: 753, department_id: 6)
City.create(name: 'SOCOTA', code: 755, department_id: 6)
City.create(name: 'SOCHA', code: 757, department_id: 6)
City.create(name: 'SOGAMOSO', code: 759, department_id: 6)
City.create(name: 'SOMONDOCO', code: 761, department_id: 6)
City.create(name: 'SORA', code: 762, department_id: 6)
City.create(name: 'SOTAQUIRA', code: 763, department_id: 6)
City.create(name: 'SORACA', code: 764, department_id: 6)
City.create(name: 'SUSACON', code: 774, department_id: 6)
City.create(name: 'SUTAMARCHAN', code: 776, department_id: 6)
City.create(name: 'SUTATENZA', code: 778, department_id: 6)
City.create(name: 'TASCO', code: 790, department_id: 6)
City.create(name: 'TENZA', code: 798, department_id: 6)
City.create(name: 'TIBANA', code: 804, department_id: 6)
City.create(name: 'TIBASOSA', code: 806, department_id: 6)
City.create(name: 'TINJACA', code: 808, department_id: 6)
City.create(name: 'TIPACOQUE', code: 810, department_id: 6)
City.create(name: 'TOCA', code: 814, department_id: 6)
City.create(name: 'TOGsI', code: 816, department_id: 6)
City.create(name: 'TOPAGA', code: 820, department_id: 6)
City.create(name: 'TOTA', code: 822, department_id: 6)
City.create(name: 'TUNUNGUA', code: 832, department_id: 6)
City.create(name: 'TURMEQUE', code: 835, department_id: 6)
City.create(name: 'TUTA', code: 837, department_id: 6)
City.create(name: 'TUTAZA', code: 839, department_id: 6)
City.create(name: 'UMBITA', code: 842, department_id: 6)
City.create(name: 'VENTAQUEMADA', code: 861, department_id: 6)
City.create(name: 'VIRACACHA', code: 879, department_id: 6)
City.create(name: 'ZETAQUIRA', code: 897, department_id: 6)

#caldas
City.create(name: 'MANIZALES', code: 1, department_id: 7)
City.create(name: 'AGUADAS', code: 13, department_id: 7)
City.create(name: 'ANSERMA', code: 42, department_id: 7)
City.create(name: 'ARANZAZU', code: 50, department_id: 7)
City.create(name: 'BELALCAZAR', code: 88, department_id: 7)
City.create(name: 'CHINCHINA', code: 174, department_id: 7)
City.create(name: 'FILADELFIA', code: 272, department_id: 7)
City.create(name: 'LA DORADA', code: 380, department_id: 7)
City.create(name: 'LA MERCED', code: 388, department_id: 7)
City.create(name: 'MANZANARES', code: 433, department_id: 7)
City.create(name: 'MARMATO', code: 442, department_id: 7)
City.create(name: 'MARQUETALIA', code: 444, department_id: 7)
City.create(name: 'MARULANDA', code: 446, department_id: 7)
City.create(name: 'NEIRA', code: 486, department_id: 7)
City.create(name: 'NORCASIA', code: 495, department_id: 7)
City.create(name: 'PACORA', code: 513, department_id: 7)
City.create(name: 'PALESTINA', code: 524, department_id: 7)
City.create(name: 'PENSILVANIA', code: 541, department_id: 7)
City.create(name: 'RIOSUCIO', code: 614, department_id: 7)
City.create(name: 'RISARALDA', code: 616, department_id: 7)
City.create(name: 'SALAMINA', code: 653, department_id: 7)
City.create(name: 'SAMANA', code: 662, department_id: 7)
City.create(name: 'SAN JOSE', code: 665, department_id: 7)
City.create(name: 'SUPIA', code: 777, department_id: 7)
City.create(name: 'VICTORIA', code: 867, department_id: 7)
City.create(name: 'VILLAMARIA', code: 873, department_id: 7)
City.create(name: 'VITERBO', code: 877, department_id: 7)

#caqueta
City.create(name: 'FLORENCIA', code: 1, department_id: 8)
City.create(name: 'ALBANIA', code: 29, department_id: 8)
City.create(name: 'BELEN DE LOS ANDAQUIES', code: 94, department_id: 8)
City.create(name: 'CARTAGENA DEL CHAIRA', code: 150, department_id: 8)
City.create(name: 'CURILLO', code: 205, department_id: 8)
City.create(name: 'EL DONCELLO', code: 247, department_id: 8)
City.create(name: 'EL PAUJIL', code: 256, department_id: 8)
City.create(name: 'LA MONTA?ITA', code: 410, department_id: 8)
City.create(name: 'MILAN', code: 460, department_id: 8)
City.create(name: 'MORELIA', code: 479, department_id: 8)
City.create(name: 'PUERTO RICO', code: 592, department_id: 8)
City.create(name: 'SAN JOSE DEL FRAGUA', code: 610, department_id: 8)
City.create(name: 'SAN VICENTE DEL CAGUAN', code: 753, department_id: 8)
City.create(name: 'SOLANO', code: 756, department_id: 8)
City.create(name: 'SOLITA', code: 785, department_id: 8)
City.create(name: 'VALPARAISO', code: 860, department_id: 8)

#casanare
City.create(name: 'YOPAL', code: 1, department_id: 9)
City.create(name: 'AGUAZUL', code: 10, department_id: 9)
City.create(name: 'CHAMEZA', code: 15, department_id: 9)
City.create(name: 'HATO COROZAL', code: 125, department_id: 9)
City.create(name: 'LA SALINA', code: 136, department_id: 9)
City.create(name: 'MANI', code: 139, department_id: 9)
City.create(name: 'MONTERREY', code: 162, department_id: 9)
City.create(name: 'NUNCHIA', code: 225, department_id: 9)
City.create(name: 'OROCUE', code: 230, department_id: 9)
City.create(name: 'PAZ DE ARIPORO', code: 250, department_id: 9)
City.create(name: 'PORE', code: 263, department_id: 9)
City.create(name: 'RECETOR', code: 279, department_id: 9)
City.create(name: 'SABANALARGA', code: 300, department_id: 9)
City.create(name: 'SACAMA', code: 315, department_id: 9)
City.create(name: 'SAN LUIS DE PALENQUE', code: 325, department_id: 9)
City.create(name: 'TAMARA', code: 400, department_id: 9)
City.create(name: 'TAURAMENA', code: 410, department_id: 9)
City.create(name: 'TRINIDAD', code: 430, department_id: 9)
City.create(name: 'VILLANUEVA', code: 440, department_id: 9)

#cauca
City.create(name: 'POPAYAN', code: 1, department_id: 10)
City.create(name: 'ALMAGUER', code: 22, department_id: 10)
City.create(name: 'ARGELIA', code: 50, department_id: 10)
City.create(name: 'BALBOA', code: 75, department_id: 10)
City.create(name: 'BOLIVAR', code: 100, department_id: 10)
City.create(name: 'BUENOS AIRES', code: 110, department_id: 10)
City.create(name: 'CAJIBIO', code: 130, department_id: 10)
City.create(name: 'CALDONO', code: 137, department_id: 10)
City.create(name: 'CALOTO', code: 142, department_id: 10)
City.create(name: 'CORINTO', code: 212, department_id: 10)
City.create(name: 'EL TAMBO', code: 256, department_id: 10)
City.create(name: 'FLORENCIA', code: 290, department_id: 10)
City.create(name: 'GUACHENE', code: 300, department_id: 10)
City.create(name: 'GUAPI', code: 318, department_id: 10)
City.create(name: 'INZA', code: 355, department_id: 10)
City.create(name: 'JAMBALO', code: 364, department_id: 10)
City.create(name: 'LA SIERRA', code: 392, department_id: 10)
City.create(name: 'LA VEGA', code: 397, department_id: 10)
City.create(name: 'LOPEZ', code: 418, department_id: 10)
City.create(name: 'MERCADERES', code: 450, department_id: 10)
City.create(name: 'MIRANDA', code: 455, department_id: 10)
City.create(name: 'MORALES', code: 473, department_id: 10)
City.create(name: 'PADILLA', code: 513, department_id: 10)
City.create(name: 'PAEZ', code: 517, department_id: 10)
City.create(name: 'PATIA', code: 532, department_id: 10)
City.create(name: 'PIAMONTE', code: 533, department_id: 10)
City.create(name: 'PIENDAMO', code: 548, department_id: 10)
City.create(name: 'PUERTO TEJADA', code: 573, department_id: 10)
City.create(name: 'PURACE', code: 585, department_id: 10)
City.create(name: 'ROSAS', code: 622, department_id: 10)
City.create(name: 'SAN SEBASTIAN', code: 693, department_id: 10)
City.create(name: 'SANTANDER DE QUILICHAO', code: 698, department_id: 10)
City.create(name: 'SANTA ROSA', code: 701, department_id: 10)
City.create(name: 'SILVIA', code: 743, department_id: 10)
City.create(name: 'SOTARA', code: 760, department_id: 10)
City.create(name: 'SUAREZ', code: 780, department_id: 10)
City.create(name: 'SUCRE', code: 785, department_id: 10)
City.create(name: 'TIMBIO', code: 807, department_id: 10)
City.create(name: 'TIMBIQUI', code: 809, department_id: 10)
City.create(name: 'TORIBIO', code: 821, department_id: 10)
City.create(name: 'TOTORO', code: 824, department_id: 10)
City.create(name: 'VILLA RICA', code: 845, department_id: 10)

#cesar
City.create(name: 'VALLEDUPAR', code: 1, department_id: 11)
City.create(name: 'AGUACHICA', code: 11, department_id: 11)
City.create(name: 'AGUSTIN CODAZZI', code: 13, department_id: 11)
City.create(name: 'ASTREA', code: 32, department_id: 11)
City.create(name: 'BECERRIL', code: 45, department_id: 11)
City.create(name: 'BOSCONIA', code: 60, department_id: 11)
City.create(name: 'CHIMICHAGUA', code: 175, department_id: 11)
City.create(name: 'CHIRIGUANA', code: 178, department_id: 11)
City.create(name: 'CURUMANI', code: 228, department_id: 11)
City.create(name: 'EL COPEY', code: 238, department_id: 11)
City.create(name: 'EL PASO', code: 250, department_id: 11)
City.create(name: 'GAMARRA', code: 295, department_id: 11)
City.create(name: 'GONZALEZ', code: 310, department_id: 11)
City.create(name: 'LA GLORIA', code: 383, department_id: 11)
City.create(name: 'LA JAGUA DE IBIRICO', code: 400, department_id: 11)
City.create(name: 'MANAURE', code: 443, department_id: 11)
City.create(name: 'PAILITAS', code: 517, department_id: 11)
City.create(name: 'PELAYA', code: 550, department_id: 11)
City.create(name: 'PUEBLO BELLO', code: 570, department_id: 11)
City.create(name: 'RIO DE ORO', code: 614, department_id: 11)
City.create(name: 'LA PAZ', code: 621, department_id: 11)
City.create(name: 'SAN ALBERTO', code: 710, department_id: 11)
City.create(name: 'SAN DIEGO', code: 750, department_id: 11)
City.create(name: 'SAN MARTIN', code: 770, department_id: 11)
City.create(name: 'TAMALAMEQUE', code: 787, department_id: 11)

#choco
City.create(name: 'QUIBDO', code: 1, department_id: 12)
City.create(name: 'ACANDI', code: 6, department_id: 12)
City.create(name: 'ALTO BAUDO', code: 25, department_id: 12)
City.create(name: 'ATRATO', code: 50, department_id: 12)
City.create(name: 'BAGADO', code: 73, department_id: 12)
City.create(name: 'BAHIA SOLANO', code: 75, department_id: 12)
City.create(name: 'BAJO BAUDO', code: 77, department_id: 12)
City.create(name: 'BOJAYA', code: 99, department_id: 12)
City.create(name: 'EL CANTON DEL SAN PABLO', code: 135, department_id: 12)
City.create(name: 'CARMEN DEL DARIEN', code: 150, department_id: 12)
City.create(name: 'CERTEGUI', code: 160, department_id: 12)
City.create(name: 'CONDOTO', code: 205, department_id: 12)
City.create(name: 'EL CARMEN DE ATRATO', code: 245, department_id: 12)
City.create(name: 'EL LITORAL DEL SAN JUAN', code: 250, department_id: 12)
City.create(name: 'ISTMINA', code: 361, department_id: 12)
City.create(name: 'JURADO', code: 372, department_id: 12)
City.create(name: 'LLORO', code: 413, department_id: 12)
City.create(name: 'MEDIO ATRATO', code: 425, department_id: 12)
City.create(name: 'MEDIO BAUDO', code: 430, department_id: 12)
City.create(name: 'MEDIO SAN JUAN', code: 450, department_id: 12)
City.create(name: 'NOVITA', code: 491, department_id: 12)
City.create(name: 'NUQUI', code: 495, department_id: 12)
City.create(name: 'RIO IRO', code: 580, department_id: 12)
City.create(name: 'RIO QUITO', code: 600, department_id: 12)
City.create(name: 'RIOSUCIO', code: 615, department_id: 12)
City.create(name: 'SAN JOSE DEL PALMAR', code: 660, department_id: 12)
City.create(name: 'SIPI', code: 745, department_id: 12)
City.create(name: 'TADO', code: 787, department_id: 12)
City.create(name: 'UNGUIA', code: 800, department_id: 12)
City.create(name: 'UNION PANAMERICANA', code: 810, department_id: 12)

#cordoba
City.create(name: 'MONTERIA', code: 1, department_id: 13)
City.create(name: 'AYAPEL', code: 68, department_id: 13)
City.create(name: 'BUENAVISTA', code: 79, department_id: 13)
City.create(name: 'CANALETE', code: 90, department_id: 13)
City.create(name: 'CERETE', code: 162, department_id: 13)
City.create(name: 'CHIMA', code: 168, department_id: 13)
City.create(name: 'CHINU', code: 182, department_id: 13)
City.create(name: 'CIENAGA DE ORO', code: 189, department_id: 13)
City.create(name: 'COTORRA', code: 300, department_id: 13)
City.create(name: 'LA APARTADA', code: 350, department_id: 13)
City.create(name: 'LORICA', code: 417, department_id: 13)
City.create(name: 'LOS CORDOBAS', code: 419, department_id: 13)
City.create(name: 'MOMIL', code: 464, department_id: 13)
City.create(name: 'MONTELIBANO', code: 466, department_id: 13)
City.create(name: 'MO?ITOS', code: 500, department_id: 13)
City.create(name: 'PLANETA RICA', code: 555, department_id: 13)
City.create(name: 'PUEBLO NUEVO', code: 570, department_id: 13)
City.create(name: 'PUERTO ESCONDIDO', code: 574, department_id: 13)
City.create(name: 'PUERTO LIBERTADOR', code: 580, department_id: 13)
City.create(name: 'PURISIMA', code: 586, department_id: 13)
City.create(name: 'SAHAGUN', code: 660, department_id: 13)
City.create(name: 'SAN ANDRES SOTAVENTO', code: 670, department_id: 13)
City.create(name: 'SAN ANTERO', code: 672, department_id: 13)
City.create(name: 'SAN BERNARDO DEL VIENTO', code: 675, department_id: 13)
City.create(name: 'SAN CARLOS', code: 678, department_id: 13)
City.create(name: 'SAN PELAYO', code: 686, department_id: 13)
City.create(name: 'TIERRALTA', code: 807, department_id: 13)
City.create(name: 'VALENCIA', code: 855, department_id: 13)

#cundinamarca
City.create(name: 'AGUA DE DIOS', code: 1, department_id: 14)
City.create(name: 'ALBAN', code: 19, department_id: 14)
City.create(name: 'ANAPOIMA', code: 35, department_id: 14)
City.create(name: 'ANOLAIMA', code: 40, department_id: 14)
City.create(name: 'ARBELAEZ', code: 53, department_id: 14)
City.create(name: 'BELTRAN', code: 86, department_id: 14)
City.create(name: 'BITUIMA', code: 95, department_id: 14)
City.create(name: 'BOJACA', code: 99, department_id: 14)
City.create(name: 'CABRERA', code: 120, department_id: 14)
City.create(name: 'CACHIPAY', code: 123, department_id: 14)
City.create(name: 'CAJICA', code: 126, department_id: 14)
City.create(name: 'CAPARRAPI', code: 148, department_id: 14)
City.create(name: 'CAQUEZA', code: 151, department_id: 14)
City.create(name: 'CARMEN DE CARUPA', code: 154, department_id: 14)
City.create(name: 'CHAGUANI', code: 168, department_id: 14)
City.create(name: 'CHIA', code: 175, department_id: 14)
City.create(name: 'CHIPAQUE', code: 178, department_id: 14)
City.create(name: 'CHOACHI', code: 181, department_id: 14)
City.create(name: 'CHOCONTA', code: 183, department_id: 14)
City.create(name: 'COGUA', code: 200, department_id: 14)
City.create(name: 'COTA', code: 214, department_id: 14)
City.create(name: 'CUCUNUBA', code: 224, department_id: 14)
City.create(name: 'EL COLEGIO', code: 245, department_id: 14)
City.create(name: 'EL PE?ON', code: 258, department_id: 14)
City.create(name: 'EL ROSAL', code: 260, department_id: 14)
City.create(name: 'FACATATIVA', code: 269, department_id: 14)
City.create(name: 'FOMEQUE', code: 279, department_id: 14)
City.create(name: 'FOSCA', code: 281, department_id: 14)
City.create(name: 'FUNZA', code: 286, department_id: 14)
City.create(name: 'FUQUENE', code: 288, department_id: 14)
City.create(name: 'FUSAGASUGA', code: 290, department_id: 14)
City.create(name: 'GACHALA', code: 293, department_id: 14)
City.create(name: 'GACHANCIPA', code: 295, department_id: 14)
City.create(name: 'GACHETA', code: 297, department_id: 14)
City.create(name: 'GAMA', code: 299, department_id: 14)
City.create(name: 'GIRARDOT', code: 307, department_id: 14)
City.create(name: 'GRANADA', code: 312, department_id: 14)
City.create(name: 'GUACHETA', code: 317, department_id: 14)
City.create(name: 'GUADUAS', code: 320, department_id: 14)
City.create(name: 'GUASCA', code: 322, department_id: 14)
City.create(name: 'GUATAQUI', code: 324, department_id: 14)
City.create(name: 'GUATAVITA', code: 326, department_id: 14)
City.create(name: 'GUAYABAL DE SIQUIMA', code: 328, department_id: 14)
City.create(name: 'GUAYABETAL', code: 335, department_id: 14)
City.create(name: 'GUTIERREZ', code: 339, department_id: 14)
City.create(name: 'JERUSALEN', code: 368, department_id: 14)
City.create(name: 'JUNIN', code: 372, department_id: 14)
City.create(name: 'LA CALERA', code: 377, department_id: 14)
City.create(name: 'LA MESA', code: 386, department_id: 14)
City.create(name: 'LA PALMA', code: 394, department_id: 14)
City.create(name: 'LA PE?A', code: 398, department_id: 14)
City.create(name: 'LA VEGA', code: 402, department_id: 14)
City.create(name: 'LENGUAZAQUE', code: 407, department_id: 14)
City.create(name: 'MACHETA', code: 426, department_id: 14)
City.create(name: 'MADRID', code: 430, department_id: 14)
City.create(name: 'MANTA', code: 436, department_id: 14)
City.create(name: 'MEDINA', code: 438, department_id: 14)
City.create(name: 'MOSQUERA', code: 473, department_id: 14)
City.create(name: 'NARI?O', code: 483, department_id: 14)
City.create(name: 'NEMOCON', code: 486, department_id: 14)
City.create(name: 'NILO', code: 488, department_id: 14)
City.create(name: 'NIMAIMA', code: 489, department_id: 14)
City.create(name: 'NOCAIMA', code: 491, department_id: 14)
City.create(name: 'VENECIA', code: 506, department_id: 14)
City.create(name: 'PACHO', code: 513, department_id: 14)
City.create(name: 'PAIME', code: 518, department_id: 14)
City.create(name: 'PANDI', code: 524, department_id: 14)
City.create(name: 'PARATEBUENO', code: 530, department_id: 14)
City.create(name: 'PASCA', code: 535, department_id: 14)
City.create(name: 'PUERTO SALGAR', code: 572, department_id: 14)
City.create(name: 'PULI', code: 580, department_id: 14)
City.create(name: 'QUEBRADANEGRA', code: 592, department_id: 14)
City.create(name: 'QUETAME', code: 594, department_id: 14)
City.create(name: 'QUIPILE', code: 596, department_id: 14)
City.create(name: 'APULO', code: 599, department_id: 14)
City.create(name: 'RICAURTE', code: 612, department_id: 14)
City.create(name: 'SAN ANTONIO DEL TEQUENDAMA', code: 645, department_id: 14)
City.create(name: 'SAN BERNARDO', code: 649, department_id: 14)
City.create(name: 'SAN CAYETANO', code: 653, department_id: 14)
City.create(name: 'SAN FRANCISCO', code: 658, department_id: 14)
City.create(name: 'SAN JUAN DE RIO SECO', code: 662, department_id: 14)
City.create(name: 'SASAIMA', code: 718, department_id: 14)
City.create(name: 'SESQUILE', code: 736, department_id: 14)
City.create(name: 'SIBATE', code: 740, department_id: 14)
City.create(name: 'SILVANIA', code: 743, department_id: 14)
City.create(name: 'SIMIJACA', code: 745, department_id: 14)
City.create(name: 'SOACHA', code: 754, department_id: 14)
City.create(name: 'SOPO', code: 758, department_id: 14)
City.create(name: 'SUBACHOQUE', code: 769, department_id: 14)
City.create(name: 'SUESCA', code: 772, department_id: 14)
City.create(name: 'SUPATA', code: 777, department_id: 14)
City.create(name: 'SUSA', code: 779, department_id: 14)
City.create(name: 'SUTATAUSA', code: 781, department_id: 14)
City.create(name: 'TABIO', code: 785, department_id: 14)
City.create(name: 'TAUSA', code: 793, department_id: 14)
City.create(name: 'TENA', code: 797, department_id: 14)
City.create(name: 'TENJO', code: 799, department_id: 14)
City.create(name: 'TIBACUY', code: 805, department_id: 14)
City.create(name: 'TIBIRITA', code: 807, department_id: 14)
City.create(name: 'TOCAIMA', code: 815, department_id: 14)
City.create(name: 'TOCANCIPA', code: 817, department_id: 14)
City.create(name: 'TOPAIPI', code: 823, department_id: 14)
City.create(name: 'UBALA', code: 839, department_id: 14)
City.create(name: 'UBAQUE', code: 841, department_id: 14)
City.create(name: 'VILLA DE SAN DIEGO DE UBATE', code: 843, department_id: 14)
City.create(name: 'UNE', code: 845, department_id: 14)
City.create(name: 'UTICA', code: 851, department_id: 14)
City.create(name: 'VERGARA', code: 862, department_id: 14)
City.create(name: 'VIANI', code: 867, department_id: 14)
City.create(name: 'VILLAGOMEZ', code: 871, department_id: 14)
City.create(name: 'VILLAPINZON', code: 873, department_id: 14)
City.create(name: 'VILLETA', code: 875, department_id: 14)
City.create(name: 'VIOTA', code: 878, department_id: 14)
City.create(name: 'YACOPI', code: 885, department_id: 14)
City.create(name: 'ZIPACON', code: 898, department_id: 14)
City.create(name: 'ZIPAQUIRA', code: 899, department_id: 14)

#d.c.
City.create(name: 'BOGOTA, D.C.', code: 1, department_id: 15)

#guainia
City.create(name: 'INIRIDA', code: 1, department_id: 16)
City.create(name: 'BARRANCO MINAS', code: 343, department_id: 16)
City.create(name: 'MAPIRIPANA', code: 663, department_id: 16)
City.create(name: 'SAN FELIPE', code: 883, department_id: 16)
City.create(name: 'PUERTO COLOMBIA', code: 884, department_id: 16)
City.create(name: 'LA GUADALUPE', code: 885, department_id: 16)
City.create(name: 'CACAHUAL', code: 886, department_id: 16)
City.create(name: 'PANA PANA', code: 887, department_id: 16)
City.create(name: 'MORICHAL', code: 888, department_id: 16)

#guaviare
City.create(name: 'SAN JOSE DEL GUAVIARE', code: 1, department_id: 17)
City.create(name: 'CALAMAR', code: 15, department_id: 17)
City.create(name: 'EL RETORNO', code: 25, department_id: 17)
City.create(name: 'MIRAFLORES', code: 200, department_id: 17)

#huila
City.create(name: 'NEIVA', code: 1, department_id: 18)
City.create(name: 'ACEVEDO', code: 6, department_id: 18)
City.create(name: 'AGRADO', code: 13, department_id: 18)
City.create(name: 'AIPE', code: 16, department_id: 18)
City.create(name: 'ALGECIRAS', code: 20, department_id: 18)
City.create(name: 'ALTAMIRA', code: 26, department_id: 18)
City.create(name: 'BARAYA', code: 78, department_id: 18)
City.create(name: 'CAMPOALEGRE', code: 132, department_id: 18)
City.create(name: 'COLOMBIA', code: 206, department_id: 18)
City.create(name: 'ELIAS', code: 244, department_id: 18)
City.create(name: 'GARZON', code: 298, department_id: 18)
City.create(name: 'GIGANTE', code: 306, department_id: 18)
City.create(name: 'GUADALUPE', code: 319, department_id: 18)
City.create(name: 'HOBO', code: 349, department_id: 18)
City.create(name: 'IQUIRA', code: 357, department_id: 18)
City.create(name: 'ISNOS', code: 359, department_id: 18)
City.create(name: 'LA ARGENTINA', code: 378, department_id: 18)
City.create(name: 'LA PLATA', code: 396, department_id: 18)
City.create(name: 'NATAGA', code: 483, department_id: 18)
City.create(name: 'OPORAPA', code: 503, department_id: 18)
City.create(name: 'PAICOL', code: 518, department_id: 18)
City.create(name: 'PALERMO', code: 524, department_id: 18)
City.create(name: 'PALESTINA', code: 530, department_id: 18)
City.create(name: 'PITAL', code: 548, department_id: 18)
City.create(name: 'PITALITO', code: 551, department_id: 18)
City.create(name: 'RIVERA', code: 615, department_id: 18)
City.create(name: 'SALADOBLANCO', code: 660, department_id: 18)
City.create(name: 'SAN AGUSTIN', code: 668, department_id: 18)
City.create(name: 'SANTA MARIA', code: 676, department_id: 18)
City.create(name: 'SUAZA', code: 770, department_id: 18)
City.create(name: 'TARQUI', code: 791, department_id: 18)
City.create(name: 'TESALIA', code: 797, department_id: 18)
City.create(name: 'TELLO', code: 799, department_id: 18)
City.create(name: 'TERUEL', code: 801, department_id: 18)
City.create(name: 'TIMANA', code: 807, department_id: 18)
City.create(name: 'VILLAVIEJA', code: 872, department_id: 18)
City.create(name: 'YAGUARA', code: 885, department_id: 18)

#la guajira
City.create(name: 'RIOHACHA', code: 1, department_id: 19)
City.create(name: 'ALBANIA', code: 35, department_id: 19)
City.create(name: 'BARRANCAS', code: 78, department_id: 19)
City.create(name: 'DIBULLA', code: 90, department_id: 19)
City.create(name: 'DISTRACCION', code: 98, department_id: 19)
City.create(name: 'EL MOLINO', code: 110, department_id: 19)
City.create(name: 'FONSECA', code: 279, department_id: 19)
City.create(name: 'HATONUEVO', code: 378, department_id: 19)
City.create(name: 'LA JAGUA DEL PILAR', code: 420, department_id: 19)
City.create(name: 'MAICAO', code: 430, department_id: 19)
City.create(name: 'MANAURE', code: 560, department_id: 19)
City.create(name: 'SAN JUAN DEL CESAR', code: 650, department_id: 19)
City.create(name: 'URIBIA', code: 847, department_id: 19)
City.create(name: 'URUMITA', code: 855, department_id: 19)
City.create(name: 'VILLANUEVA', code: 874, department_id: 19)

#magdalena
City.create(name: 'SANTA MARTA', code: 1, department_id: 20)
City.create(name: 'ALGARROBO', code: 30, department_id: 20)
City.create(name: 'ARACATACA', code: 53, department_id: 20)
City.create(name: 'ARIGUANI', code: 58, department_id: 20)
City.create(name: 'CERRO SAN ANTONIO', code: 161, department_id: 20)
City.create(name: 'CHIBOLO', code: 170, department_id: 20)
City.create(name: 'CIENAGA', code: 189, department_id: 20)
City.create(name: 'CONCORDIA', code: 205, department_id: 20)
City.create(name: 'EL BANCO', code: 245, department_id: 20)
City.create(name: 'EL PI?ON', code: 258, department_id: 20)
City.create(name: 'EL RETEN', code: 268, department_id: 20)
City.create(name: 'FUNDACION', code: 288, department_id: 20)
City.create(name: 'GUAMAL', code: 318, department_id: 20)
City.create(name: 'NUEVA GRANADA', code: 460, department_id: 20)
City.create(name: 'PEDRAZA', code: 541, department_id: 20)
City.create(name: 'PIJI?O DEL CARMEN', code: 545, department_id: 20)
City.create(name: 'PIVIJAY', code: 551, department_id: 20)
City.create(name: 'PLATO', code: 555, department_id: 20)
City.create(name: 'PUEBLOVIEJO', code: 570, department_id: 20)
City.create(name: 'REMOLINO', code: 605, department_id: 20)
City.create(name: 'SABANAS DE SAN ANGEL', code: 660, department_id: 20)
City.create(name: 'SALAMINA', code: 675, department_id: 20)
City.create(name: 'SAN SEBASTIAN DE BUENAVISTA', code: 692, department_id: 20)
City.create(name: 'SAN ZENON', code: 703, department_id: 20)
City.create(name: 'SANTA ANA', code: 707, department_id: 20)
City.create(name: 'SANTA BARBARA DE PINTO', code: 720, department_id: 20)
City.create(name: 'SITIONUEVO', code: 745, department_id: 20)
City.create(name: 'TENERIFE', code: 798, department_id: 20)
City.create(name: 'ZAPAYAN', code: 960, department_id: 20)
City.create(name: 'ZONA BANANERA', code: 980, department_id: 20)

#meta
City.create(name: 'VILLAVICENCIO', code: 1, department_id: 21)
City.create(name: 'ACACIAS', code: 6, department_id: 21)
City.create(name: 'BARRANCA DE UPIA', code: 110, department_id: 21)
City.create(name: 'CABUYARO', code: 124, department_id: 21)
City.create(name: 'CASTILLA LA NUEVA', code: 150, department_id: 21)
City.create(name: 'CUBARRAL', code: 223, department_id: 21)
City.create(name: 'CUMARAL', code: 226, department_id: 21)
City.create(name: 'EL CALVARIO', code: 245, department_id: 21)
City.create(name: 'EL CASTILLO', code: 251, department_id: 21)
City.create(name: 'EL DORADO', code: 270, department_id: 21)
City.create(name: 'FUENTE DE ORO', code: 287, department_id: 21)
City.create(name: 'GRANADA', code: 313, department_id: 21)
City.create(name: 'GUAMAL', code: 318, department_id: 21)
City.create(name: 'MAPIRIPAN', code: 325, department_id: 21)
City.create(name: 'MESETAS', code: 330, department_id: 21)
City.create(name: 'LA MACARENA', code: 350, department_id: 21)
City.create(name: 'URIBE', code: 370, department_id: 21)
City.create(name: 'LEJANIAS', code: 400, department_id: 21)
City.create(name: 'PUERTO CONCORDIA', code: 450, department_id: 21)
City.create(name: 'PUERTO GAITAN', code: 568, department_id: 21)
City.create(name: 'PUERTO LOPEZ', code: 573, department_id: 21)
City.create(name: 'PUERTO LLERAS', code: 577, department_id: 21)
City.create(name: 'PUERTO RICO', code: 590, department_id: 21)
City.create(name: 'RESTREPO', code: 606, department_id: 21)
City.create(name: 'SAN CARLOS DE GUAROA', code: 680, department_id: 21)
City.create(name: 'SAN JUAN DE ARAMA', code: 683, department_id: 21)
City.create(name: 'SAN JUANITO', code: 686, department_id: 21)
City.create(name: 'SAN MARTIN', code: 689, department_id: 21)
City.create(name: 'VISTAHERMOSA', code: 711, department_id: 21)

#nariño
City.create(name: 'PASTO', code: 1, department_id: 22)
City.create(name: 'ALBAN', code: 19, department_id: 22)
City.create(name: 'ALDANA', code: 22, department_id: 22)
City.create(name: 'ANCUYA', code: 36, department_id: 22)
City.create(name: 'ARBOLEDA', code: 51, department_id: 22)
City.create(name: 'BARBACOAS', code: 79, department_id: 22)
City.create(name: 'BELEN', code: 83, department_id: 22)
City.create(name: 'BUESACO', code: 110, department_id: 22)
City.create(name: 'COLON', code: 203, department_id: 22)
City.create(name: 'CONSACA', code: 207, department_id: 22)
City.create(name: 'CONTADERO', code: 210, department_id: 22)
City.create(name: 'CORDOBA', code: 215, department_id: 22)
City.create(name: 'CUASPUD', code: 224, department_id: 22)
City.create(name: 'CUMBAL', code: 227, department_id: 22)
City.create(name: 'CUMBITARA', code: 233, department_id: 22)
City.create(name: 'CHACHAGsI', code: 240, department_id: 22)
City.create(name: 'EL CHARCO', code: 250, department_id: 22)
City.create(name: 'EL PE?OL', code: 254, department_id: 22)
City.create(name: 'EL ROSARIO', code: 256, department_id: 22)
City.create(name: 'EL TABLON DE GOMEZ', code: 258, department_id: 22)
City.create(name: 'EL TAMBO', code: 260, department_id: 22)
City.create(name: 'FUNES', code: 287, department_id: 22)
City.create(name: 'GUACHUCAL', code: 317, department_id: 22)
City.create(name: 'GUAITARILLA', code: 320, department_id: 22)
City.create(name: 'GUALMATAN', code: 323, department_id: 22)
City.create(name: 'ILES', code: 352, department_id: 22)
City.create(name: 'IMUES', code: 354, department_id: 22)
City.create(name: 'IPIALES', code: 356, department_id: 22)
City.create(name: 'LA CRUZ', code: 378, department_id: 22)
City.create(name: 'LA FLORIDA', code: 381, department_id: 22)
City.create(name: 'LA LLANADA', code: 385, department_id: 22)
City.create(name: 'LA TOLA', code: 390, department_id: 22)
City.create(name: 'LA UNION', code: 399, department_id: 22)
City.create(name: 'LEIVA', code: 405, department_id: 22)
City.create(name: 'LINARES', code: 411, department_id: 22)
City.create(name: 'LOS ANDES', code: 418, department_id: 22)
City.create(name: 'MAGsI', code: 427, department_id: 22)
City.create(name: 'MALLAMA', code: 435, department_id: 22)
City.create(name: 'MOSQUERA', code: 473, department_id: 22)
City.create(name: 'NARI?O', code: 480, department_id: 22)
City.create(name: 'OLAYA HERRERA', code: 490, department_id: 22)
City.create(name: 'OSPINA', code: 506, department_id: 22)
City.create(name: 'FRANCISCO PIZARRO', code: 520, department_id: 22)
City.create(name: 'POLICARPA', code: 540, department_id: 22)
City.create(name: 'POTOSI', code: 560, department_id: 22)
City.create(name: 'PROVIDENCIA', code: 565, department_id: 22)
City.create(name: 'PUERRES', code: 573, department_id: 22)
City.create(name: 'PUPIALES', code: 585, department_id: 22)
City.create(name: 'RICAURTE', code: 612, department_id: 22)
City.create(name: 'ROBERTO PAYAN', code: 621, department_id: 22)
City.create(name: 'SAMANIEGO', code: 678, department_id: 22)
City.create(name: 'SANDONA', code: 683, department_id: 22)
City.create(name: 'SAN BERNARDO', code: 685, department_id: 22)
City.create(name: 'SAN LORENZO', code: 687, department_id: 22)
City.create(name: 'SAN PABLO', code: 693, department_id: 22)
City.create(name: 'SAN PEDRO DE CARTAGO', code: 694, department_id: 22)
City.create(name: 'SANTA BARBARA', code: 696, department_id: 22)
City.create(name: 'SANTACRUZ', code: 699, department_id: 22)
City.create(name: 'SAPUYES', code: 720, department_id: 22)
City.create(name: 'TAMINANGO', code: 786, department_id: 22)
City.create(name: 'TANGUA', code: 788, department_id: 22)
City.create(name: 'SAN ANDRES DE TUMACO', code: 835, department_id: 22)
City.create(name: 'TUQUERRES', code: 838, department_id: 22)
City.create(name: 'YACUANQUER', code: 885, department_id: 22)

#n. santander
City.create(name: 'CUCUTA', code: 1, department_id: 23)
City.create(name: 'ABREGO', code: 3, department_id: 23)
City.create(name: 'ARBOLEDAS', code: 51, department_id: 23)
City.create(name: 'BOCHALEMA', code: 99, department_id: 23)
City.create(name: 'BUCARASICA', code: 109, department_id: 23)
City.create(name: 'CACOTA', code: 125, department_id: 23)
City.create(name: 'CACHIRA', code: 128, department_id: 23)
City.create(name: 'CHINACOTA', code: 172, department_id: 23)
City.create(name: 'CHITAGA', code: 174, department_id: 23)
City.create(name: 'CONVENCION', code: 206, department_id: 23)
City.create(name: 'CUCUTILLA', code: 223, department_id: 23)
City.create(name: 'DURANIA', code: 239, department_id: 23)
City.create(name: 'EL CARMEN', code: 245, department_id: 23)
City.create(name: 'EL TARRA', code: 250, department_id: 23)
City.create(name: 'EL ZULIA', code: 261, department_id: 23)
City.create(name: 'GRAMALOTE', code: 313, department_id: 23)
City.create(name: 'HACARI', code: 344, department_id: 23)
City.create(name: 'HERRAN', code: 347, department_id: 23)
City.create(name: 'LABATECA', code: 377, department_id: 23)
City.create(name: 'LA ESPERANZA', code: 385, department_id: 23)
City.create(name: 'LA PLAYA', code: 398, department_id: 23)
City.create(name: 'LOS PATIOS', code: 405, department_id: 23)
City.create(name: 'LOURDES', code: 418, department_id: 23)
City.create(name: 'MUTISCUA', code: 480, department_id: 23)
City.create(name: 'OCA?A', code: 498, department_id: 23)
City.create(name: 'PAMPLONA', code: 518, department_id: 23)
City.create(name: 'PAMPLONITA', code: 520, department_id: 23)
City.create(name: 'PUERTO SANTANDER', code: 553, department_id: 23)
City.create(name: 'RAGONVALIA', code: 599, department_id: 23)
City.create(name: 'SALAZAR', code: 660, department_id: 23)
City.create(name: 'SAN CALIXTO', code: 670, department_id: 23)
City.create(name: 'SAN CAYETANO', code: 673, department_id: 23)
City.create(name: 'SANTIAGO', code: 680, department_id: 23)
City.create(name: 'SARDINATA', code: 720, department_id: 23)
City.create(name: 'SILOS', code: 743, department_id: 23)
City.create(name: 'TEORAMA', code: 800, department_id: 23)
City.create(name: 'TIBU', code: 810, department_id: 23)
City.create(name: 'TOLEDO', code: 820, department_id: 23)
City.create(name: 'VILLA CARO', code: 871, department_id: 23)
City.create(name: 'VILLA DEL ROSARIO', code: 874, department_id: 23)

#putumayo
City.create(name: 'MOCOA', code: 1, department_id: 24)
City.create(name: 'COLON', code: 219, department_id: 24)
City.create(name: 'ORITO', code: 320, department_id: 24)
City.create(name: 'PUERTO ASIS', code: 568, department_id: 24)
City.create(name: 'PUERTO CAICEDO', code: 569, department_id: 24)
City.create(name: 'PUERTO GUZMAN', code: 571, department_id: 24)
City.create(name: 'LEGUIZAMO', code: 573, department_id: 24)
City.create(name: 'SIBUNDOY', code: 749, department_id: 24)
City.create(name: 'SAN FRANCISCO', code: 755, department_id: 24)
City.create(name: 'SAN MIGUEL', code: 757, department_id: 24)
City.create(name: 'SANTIAGO', code: 760, department_id: 24)
City.create(name: 'VALLE DEL GUAMUEZ', code: 865, department_id: 24)
City.create(name: 'VILLAGARZON', code: 885, department_id: 24)

#quindio
City.create(name: 'ARMENIA', code: 1, department_id: 25)
City.create(name: 'BUENAVISTA', code: 111, department_id: 25)
City.create(name: 'CALARCA', code: 130, department_id: 25)
City.create(name: 'CIRCASIA', code: 190, department_id: 25)
City.create(name: 'CORDOBA', code: 212, department_id: 25)
City.create(name: 'FILANDIA', code: 272, department_id: 25)
City.create(name: 'GENOVA', code: 302, department_id: 25)
City.create(name: 'LA TEBAIDA', code: 401, department_id: 25)
City.create(name: 'MONTENEGRO', code: 470, department_id: 25)
City.create(name: 'PIJAO', code: 548, department_id: 25)
City.create(name: 'QUIMBAYA', code: 594, department_id: 25)
City.create(name: 'SALENTO', code: 690, department_id: 25)

#risaralda
City.create(name: 'PEREIRA', code: 1, department_id: 26)
City.create(name: 'APIA', code: 45, department_id: 26)
City.create(name: 'BALBOA', code: 75, department_id: 26)
City.create(name: 'BELEN DE UMBRIA', code: 88, department_id: 26)
City.create(name: 'DOSQUEBRADAS', code: 170, department_id: 26)
City.create(name: 'GUATICA', code: 318, department_id: 26)
City.create(name: 'LA CELIA', code: 383, department_id: 26)
City.create(name: 'LA VIRGINIA', code: 400, department_id: 26)
City.create(name: 'MARSELLA', code: 440, department_id: 26)
City.create(name: 'MISTRATO', code: 456, department_id: 26)
City.create(name: 'PUEBLO RICO', code: 572, department_id: 26)
City.create(name: 'QUINCHIA', code: 594, department_id: 26)
City.create(name: 'SANTA ROSA DE CABAL', code: 682, department_id: 26)
City.create(name: 'SANTUARIO', code: 687, department_id: 26)

#san andres
City.create(name: 'SAN ANDRES', code: 1, department_id: 27)
City.create(name: 'PROVIDENCIA', code: 564, department_id: 27)

#santander
City.create(name: 'BUCARAMANGA', code: 1, department_id: 28)
City.create(name: 'AGUADA', code: 13, department_id: 28)
City.create(name: 'ALBANIA', code: 20, department_id: 28)
City.create(name: 'ARATOCA', code: 51, department_id: 28)
City.create(name: 'BARBOSA', code: 77, department_id: 28)
City.create(name: 'BARICHARA', code: 79, department_id: 28)
City.create(name: 'BARRANCABERMEJA', code: 81, department_id: 28)
City.create(name: 'BETULIA', code: 92, department_id: 28)
City.create(name: 'BOLIVAR', code: 101, department_id: 28)
City.create(name: 'CABRERA', code: 121, department_id: 28)
City.create(name: 'CALIFORNIA', code: 132, department_id: 28)
City.create(name: 'CAPITANEJO', code: 147, department_id: 28)
City.create(name: 'CARCASI', code: 152, department_id: 28)
City.create(name: 'CEPITA', code: 160, department_id: 28)
City.create(name: 'CERRITO', code: 162, department_id: 28)
City.create(name: 'CHARALA', code: 167, department_id: 28)
City.create(name: 'CHARTA', code: 169, department_id: 28)
City.create(name: 'CHIMA', code: 176, department_id: 28)
City.create(name: 'CHIPATA', code: 179, department_id: 28)
City.create(name: 'CIMITARRA', code: 190, department_id: 28)
City.create(name: 'CONCEPCION', code: 207, department_id: 28)
City.create(name: 'CONFINES', code: 209, department_id: 28)
City.create(name: 'CONTRATACION', code: 211, department_id: 28)
City.create(name: 'COROMORO', code: 217, department_id: 28)
City.create(name: 'CURITI', code: 229, department_id: 28)
City.create(name: 'EL CARMEN DE CHUCURI', code: 235, department_id: 28)
City.create(name: 'EL GUACAMAYO', code: 245, department_id: 28)
City.create(name: 'EL PE?ON', code: 250, department_id: 28)
City.create(name: 'EL PLAYON', code: 255, department_id: 28)
City.create(name: 'ENCINO', code: 264, department_id: 28)
City.create(name: 'ENCISO', code: 266, department_id: 28)
City.create(name: 'FLORIAN', code: 271, department_id: 28)
City.create(name: 'FLORIDABLANCA', code: 276, department_id: 28)
City.create(name: 'GALAN', code: 296, department_id: 28)
City.create(name: 'GAMBITA', code: 298, department_id: 28)
City.create(name: 'GIRON', code: 307, department_id: 28)
City.create(name: 'GUACA', code: 318, department_id: 28)
City.create(name: 'GUADALUPE', code: 320, department_id: 28)
City.create(name: 'GUAPOTA', code: 322, department_id: 28)
City.create(name: 'GUAVATA', code: 324, department_id: 28)
City.create(name: 'GsEPSA', code: 327, department_id: 28)
City.create(name: 'HATO', code: 344, department_id: 28)
City.create(name: 'JESUS MARIA', code: 368, department_id: 28)
City.create(name: 'JORDAN', code: 370, department_id: 28)
City.create(name: 'LA BELLEZA', code: 377, department_id: 28)
City.create(name: 'LANDAZURI', code: 385, department_id: 28)
City.create(name: 'LA PAZ', code: 397, department_id: 28)
City.create(name: 'LEBRIJA', code: 406, department_id: 28)
City.create(name: 'LOS SANTOS', code: 418, department_id: 28)
City.create(name: 'MACARAVITA', code: 425, department_id: 28)
City.create(name: 'MALAGA', code: 432, department_id: 28)
City.create(name: 'MATANZA', code: 444, department_id: 28)
City.create(name: 'MOGOTES', code: 464, department_id: 28)
City.create(name: 'MOLAGAVITA', code: 468, department_id: 28)
City.create(name: 'OCAMONTE', code: 498, department_id: 28)
City.create(name: 'OIBA', code: 500, department_id: 28)
City.create(name: 'ONZAGA', code: 502, department_id: 28)
City.create(name: 'PALMAR', code: 522, department_id: 28)
City.create(name: 'PALMAS DEL SOCORRO', code: 524, department_id: 28)
City.create(name: 'PARAMO', code: 533, department_id: 28)
City.create(name: 'PIEDECUESTA', code: 547, department_id: 28)
City.create(name: 'PINCHOTE', code: 549, department_id: 28)
City.create(name: 'PUENTE NACIONAL', code: 572, department_id: 28)
City.create(name: 'PUERTO PARRA', code: 573, department_id: 28)
City.create(name: 'PUERTO WILCHES', code: 575, department_id: 28)
City.create(name: 'RIONEGRO', code: 615, department_id: 28)
City.create(name: 'SABANA DE TORRES', code: 655, department_id: 28)
City.create(name: 'SAN ANDRES', code: 669, department_id: 28)
City.create(name: 'SAN BENITO', code: 673, department_id: 28)
City.create(name: 'SAN GIL', code: 679, department_id: 28)
City.create(name: 'SAN JOAQUIN', code: 682, department_id: 28)
City.create(name: 'SAN JOSE DE MIRANDA', code: 684, department_id: 28)
City.create(name: 'SAN MIGUEL', code: 686, department_id: 28)
City.create(name: 'SAN VICENTE DE CHUCURI', code: 689, department_id: 28)
City.create(name: 'SANTA BARBARA', code: 705, department_id: 28)
City.create(name: 'SANTA HELENA DEL OPON', code: 720, department_id: 28)
City.create(name: 'SIMACOTA', code: 745, department_id: 28)
City.create(name: 'SOCORRO', code: 755, department_id: 28)
City.create(name: 'SUAITA', code: 770, department_id: 28)
City.create(name: 'SUCRE', code: 773, department_id: 28)
City.create(name: 'SURATA', code: 780, department_id: 28)
City.create(name: 'TONA', code: 820, department_id: 28)
City.create(name: 'VALLE DE SAN JOSE', code: 855, department_id: 28)
City.create(name: 'VELEZ', code: 861, department_id: 28)
City.create(name: 'VETAS', code: 867, department_id: 28)
City.create(name: 'VILLANUEVA', code: 872, department_id: 28)
City.create(name: 'ZAPATOCA', code: 895, department_id: 28)

#sucre
City.create(name: 'SINCELEJO', code: 1, department_id: 29)
City.create(name: 'BUENAVISTA', code: 110, department_id: 29)
City.create(name: 'CAIMITO', code: 124, department_id: 29)
City.create(name: 'COLOSO', code: 204, department_id: 29)
City.create(name: 'COROZAL', code: 215, department_id: 29)
City.create(name: 'COVE?AS', code: 221, department_id: 29)
City.create(name: 'CHALAN', code: 230, department_id: 29)
City.create(name: 'EL ROBLE', code: 233, department_id: 29)
City.create(name: 'GALERAS', code: 235, department_id: 29)
City.create(name: 'GUARANDA', code: 265, department_id: 29)
City.create(name: 'LA UNION', code: 400, department_id: 29)
City.create(name: 'LOS PALMITOS', code: 418, department_id: 29)
City.create(name: 'MAJAGUAL', code: 429, department_id: 29)
City.create(name: 'MORROA', code: 473, department_id: 29)
City.create(name: 'OVEJAS', code: 508, department_id: 29)
City.create(name: 'PALMITO', code: 523, department_id: 29)
City.create(name: 'SAMPUES', code: 670, department_id: 29)
City.create(name: 'SAN BENITO ABAD', code: 678, department_id: 29)
City.create(name: 'SAN JUAN DE BETULIA', code: 702, department_id: 29)
City.create(name: 'SAN MARCOS', code: 708, department_id: 29)
City.create(name: 'SAN ONOFRE', code: 713, department_id: 29)
City.create(name: 'SAN PEDRO', code: 717, department_id: 29)
City.create(name: 'SAN LUIS DE SINCE', code: 742, department_id: 29)
City.create(name: 'SUCRE', code: 771, department_id: 29)
City.create(name: 'SANTIAGO DE TOLU', code: 820, department_id: 29)
City.create(name: 'TOLU VIEJO', code: 823, department_id: 29)

#tolima
City.create(name: 'IBAGUE', code: 1, department_id: 30)
City.create(name: 'ALPUJARRA', code: 24, department_id: 30)
City.create(name: 'ALVARADO', code: 26, department_id: 30)
City.create(name: 'AMBALEMA', code: 30, department_id: 30)
City.create(name: 'ANZOATEGUI', code: 43, department_id: 30)
City.create(name: 'ARMERO', code: 55, department_id: 30)
City.create(name: 'ATACO', code: 67, department_id: 30)
City.create(name: 'CAJAMARCA', code: 124, department_id: 30)
City.create(name: 'CARMEN DE APICALA', code: 148, department_id: 30)
City.create(name: 'CASABIANCA', code: 152, department_id: 30)
City.create(name: 'CHAPARRAL', code: 168, department_id: 30)
City.create(name: 'COELLO', code: 200, department_id: 30)
City.create(name: 'COYAIMA', code: 217, department_id: 30)
City.create(name: 'CUNDAY', code: 226, department_id: 30)
City.create(name: 'DOLORES', code: 236, department_id: 30)
City.create(name: 'ESPINAL', code: 268, department_id: 30)
City.create(name: 'FALAN', code: 270, department_id: 30)
City.create(name: 'FLANDES', code: 275, department_id: 30)
City.create(name: 'FRESNO', code: 283, department_id: 30)
City.create(name: 'GUAMO', code: 319, department_id: 30)
City.create(name: 'HERVEO', code: 347, department_id: 30)
City.create(name: 'HONDA', code: 349, department_id: 30)
City.create(name: 'ICONONZO', code: 352, department_id: 30)
City.create(name: 'LERIDA', code: 408, department_id: 30)
City.create(name: 'LIBANO', code: 411, department_id: 30)
City.create(name: 'MARIQUITA', code: 443, department_id: 30)
City.create(name: 'MELGAR', code: 449, department_id: 30)
City.create(name: 'MURILLO', code: 461, department_id: 30)
City.create(name: 'NATAGAIMA', code: 483, department_id: 30)
City.create(name: 'ORTEGA', code: 504, department_id: 30)
City.create(name: 'PALOCABILDO', code: 520, department_id: 30)
City.create(name: 'PIEDRAS', code: 547, department_id: 30)
City.create(name: 'PLANADAS', code: 555, department_id: 30)
City.create(name: 'PRADO', code: 563, department_id: 30)
City.create(name: 'PURIFICACION', code: 585, department_id: 30)
City.create(name: 'RIOBLANCO', code: 616, department_id: 30)
City.create(name: 'RONCESVALLES', code: 622, department_id: 30)
City.create(name: 'ROVIRA', code: 624, department_id: 30)
City.create(name: 'SALDA?A', code: 671, department_id: 30)
City.create(name: 'SAN ANTONIO', code: 675, department_id: 30)
City.create(name: 'SAN LUIS', code: 678, department_id: 30)
City.create(name: 'SANTA ISABEL', code: 686, department_id: 30)
City.create(name: 'SUAREZ', code: 770, department_id: 30)
City.create(name: 'VALLE DE SAN JUAN', code: 854, department_id: 30)
City.create(name: 'VENADILLO', code: 861, department_id: 30)
City.create(name: 'VILLAHERMOSA', code: 870, department_id: 30)
City.create(name: 'VILLARRICA', code: 873, department_id: 30)

#valle del cauca
City.create(name: 'CALI', code: 1, department_id: 31)
City.create(name: 'ALCALA', code: 20, department_id: 31)
City.create(name: 'ANDALUCIA', code: 36, department_id: 31)
City.create(name: 'ANSERMANUEVO', code: 41, department_id: 31)
City.create(name: 'ARGELIA', code: 54, department_id: 31)
City.create(name: 'BOLIVAR', code: 100, department_id: 31)
City.create(name: 'BUENAVENTURA', code: 109, department_id: 31)
City.create(name: 'GUADALAJARA DE BUGA', code: 111, department_id: 31)
City.create(name: 'BUGALAGRANDE', code: 113, department_id: 31)
City.create(name: 'CAICEDONIA', code: 122, department_id: 31)
City.create(name: 'CALIMA', code: 126, department_id: 31)
City.create(name: 'CANDELARIA', code: 130, department_id: 31)
City.create(name: 'CARTAGO', code: 147, department_id: 31)
City.create(name: 'DAGUA', code: 233, department_id: 31)
City.create(name: 'EL AGUILA', code: 243, department_id: 31)
City.create(name: 'EL CAIRO', code: 246, department_id: 31)
City.create(name: 'EL CERRITO', code: 248, department_id: 31)
City.create(name: 'EL DOVIO', code: 250, department_id: 31)
City.create(name: 'FLORIDA', code: 275, department_id: 31)
City.create(name: 'GINEBRA', code: 306, department_id: 31)
City.create(name: 'GUACARI', code: 318, department_id: 31)
City.create(name: 'JAMUNDI', code: 364, department_id: 31)
City.create(name: 'LA CUMBRE', code: 377, department_id: 31)
City.create(name: 'LA UNION', code: 400, department_id: 31)
City.create(name: 'LA VICTORIA', code: 403, department_id: 31)
City.create(name: 'OBANDO', code: 497, department_id: 31)
City.create(name: 'PALMIRA', code: 520, department_id: 31)
City.create(name: 'PRADERA', code: 563, department_id: 31)
City.create(name: 'RESTREPO', code: 606, department_id: 31)
City.create(name: 'RIOFRIO', code: 616, department_id: 31)
City.create(name: 'ROLDANILLO', code: 622, department_id: 31)
City.create(name: 'SAN PEDRO', code: 670, department_id: 31)
City.create(name: 'SEVILLA', code: 736, department_id: 31)
City.create(name: 'TORO', code: 823, department_id: 31)
City.create(name: 'TRUJILLO', code: 828, department_id: 31)
City.create(name: 'TULUA', code: 834, department_id: 31)
City.create(name: 'ULLOA', code: 845, department_id: 31)
City.create(name: 'VERSALLES', code: 863, department_id: 31)
City.create(name: 'VIJES', code: 869, department_id: 31)
City.create(name: 'YOTOCO', code: 890, department_id: 31)
City.create(name: 'YUMBO', code: 892, department_id: 31)
City.create(name: 'ZARZAL', code: 895, department_id: 31)

#vaupez
City.create(name: 'MITU', code: 1, department_id: 32)
City.create(name: 'CARURU', code: 161, department_id: 32)
City.create(name: 'PACOA', code: 511, department_id: 32)
City.create(name: 'TARAIRA', code: 666, department_id: 32)
City.create(name: 'PAPUNAUA', code: 777, department_id: 32)
City.create(name: 'YAVARATE', code: 889, department_id: 32)

#vichada
City.create(name: 'PUERTO CARRENO', code: 1, department_id: 33)
City.create(name: 'LA PRIMAVERA', code: 524, department_id: 33)
City.create(name: 'SANTA ROSALIA', code: 624, department_id: 33)
City.create(name: 'CUMARIBO', code: 773, department_id: 33)


